name: patricklalonde
favicon: null
layout_spectrum: 0.74294
typography_spectrum: 0.48833
title: TEST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#32a378'
    - '#1e7d55'
    - '#fefefe'
    - '#bdcfc3'
    - '#8fb09b'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
