typography_spectrum: 0.48833
color:
  brandColors:
    - '#32a378'
    - '#1e7d55'
    - '#fefefe'
    - '#bdcfc3'
    - '#8fb09b'
  brandStrength: 0.3125
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5071685
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5286738
analytics:
  google: null
  facebook: null
  twitter: null
name: test-pt-test
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: BIKE
    id: ec464251-f9cb-4903-a62c-a043483987fb
    type: content
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Patrick Lalonde
purpose: []
