name: patricklalonde
favicon: null
layout_spectrum: 0.6096471440978348
typography_spectrum: 0.9633931205607951
title: TEST
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#32a378'
    - '#1e7d55'
    - '#fefefe'
    - '#bdcfc3'
    - '#8fb09b'
  brandStrength: 0.6875
  lightness: 0.375
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
